/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package gradle.plugin

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class GradlePluginPlugin implements Plugin<Project> {

    void apply(Project project) {
        project.pluginManager.apply('base')
    }

}
