/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package wa.serenity

import org.gradle.api.*
import org.gradle.api.tasks.testing.Test

/**
 * A simple 'hello world' plugin.
 */
class WaSerenityPlugin implements Plugin<Project> {

    static final String SERENITY_CORE_VERSION = '2.3.6'
    static final String SERENITY_CUCUMBER_VERSION = '2.3.6'
    static final String ASSERTJ_VERSION = '3.8.0'
    static final String LOGBACK_VERSION = '1.2.3'

    static final String IMPLEMENTATION = 'implementation'
    static final String TEST_IMPLEMENTATION = 'testImplementation'

    void apply(Project project) {
        project.ext.serenityCoreVersion = SERENITY_CORE_VERSION
        project.ext.serenityCucumberVersion = SERENITY_CUCUMBER_VERSION
        project.ext.assertjVersion = ASSERTJ_VERSION
        project.ext.logbackVersion = LOGBACK_VERSION

        configurePlugins(project)
        configureDependencies(project)
        configureTest(project.tasks.getByName('test'))
    }

    void configurePlugins(final Project project) {
        project.pluginManager.apply('wa.base')
        project.pluginManager.apply('java')
        project.pluginManager.apply('groovy')
        project.pluginManager.apply('net.serenity-bdd.aggregator')
    }

    void configureDependencies(final Project project) {
        project.afterEvaluate {
            project.dependencies.add(IMPLEMENTATION,
                    "ch.qos.logback:logback-classic:${project.logbackVersion}")
            project.dependencies.add(TEST_IMPLEMENTATION,
                    "net.serenity-bdd:serenity-core:${project.serenityCoreVersion}")
            project.dependencies.add(TEST_IMPLEMENTATION,
                    "net.serenity-bdd:serenity-junit:${project.serenityCoreVersion}")
            project.dependencies.add(TEST_IMPLEMENTATION,
                    "net.serenity-bdd:serenity-rest-assured:${project.serenityCoreVersion}")
            project.dependencies.add(TEST_IMPLEMENTATION,
                    "net.serenity-bdd:serenity-screenplay:${project.serenityCoreVersion}")
            project.dependencies.add(TEST_IMPLEMENTATION,
                    "net.serenity-bdd:serenity-screenplay-rest:${project.serenityCoreVersion}")
            project.dependencies.add(TEST_IMPLEMENTATION,
                    "net.serenity-bdd:serenity-screenplay-webdriver:${project.serenityCoreVersion}")
            project.dependencies.add(TEST_IMPLEMENTATION,
                    "net.serenity-bdd:serenity-cucumber6:${project.serenityCucumberVersion}")
            project.dependencies.add(TEST_IMPLEMENTATION,
                    "org.assertj:assertj-core:${project.assertjVersion}")
        }
    }

    void configureTest(final Test task) {
        task.testLogging.showStandardStreams = true
        task.systemProperties(System.properties)
        task.finalizedBy('aggregate')
    }

}
