/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package wa.base

import org.gradle.testfixtures.ProjectBuilder

import spock.lang.Specification

/**
 * A simple unit test for the 'wa.gradle.eclipse.greeting' plugin.
 */
class WaBasePluginTest extends Specification {

    def "plugin registers base tasks"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply('wa.base')

        then:
        project.tasks.findByName('assemble') != null
        project.tasks.findByName('build') != null
        project.tasks.findByName('check') != null
        project.tasks.findByName('clean') != null
        project.tasks.findByName('assembleDist') != null
        project.tasks.findByName('installDist') != null
    }

}
