/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package wa.docker

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class WaDockerPlugin implements Plugin<Project> {

    void apply(Project project) {
        project.pluginManager.apply('wa.base')
        project.pluginManager.apply('com.palantir.docker')
        project.pluginManager.apply('com.palantir.docker-compose')

        if (project.file('Dockerfile').exists()) {
            project.tasks.build.dependsOn('dockerTag')
        }
    }

}
